version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: audio_sop_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/audio_sop
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  db:
    image: postgres:14
    container_name: audio_sop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audio_sop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
